module(name = "demo")
bazel_dep(name = "rules_cc", version = "0.2.22")
bazel_dep(name = "fmt", version = "12.1.0")

single_version_override(
    module_name = "fmt",
    version = "12.1.0",
    patches = [
        ":fix.patch",
    ],
)

git_override(
    module_name = "rules_cc",
    remote = "https://github.com/PikachuHyA/rules_cc.git",
    commit = "9e09a30d65462420c22fac51fc8c3b861cc04f71"
)

#local_path_override(
#    module_name = "rules_cc",
#    path = "D:\\code\\module_demo\\rules_cc",
#)